name: ðŸš€ã€€Create Release Branch
on:
  push:
    branches:
      - master
jobs:
  crb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "${{ github.sha }}" > .releasing
      - uses: wow-actions/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token
      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ env.bot_token }}
          branch: semantic-release
          commit-message: "trigger semantic release..."
          delete-branch: true
          labels: semantic-release
          title: "chore: semantic release [skip ci]"
          body: |
            Your **[semantic-release-monorepo](https://github.com/bubkoo/semantic-release-monorepo)** bot base on **[semantic-release](https://github.com/semantic-release/semantic-release)** :package::rocket:`
