blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Questions & Answers
    url: https://github.com/antvis/X6/discussions/categories/q-a
    about: Please ask and answer questions here â†’
  - name: ğŸ’¬ é—®é¢˜å’Œç­”æ¡ˆ
    url: https://github.com/antvis/X6/discussions/categories/q-a
    about: åœ¨æ­¤æé—®å¹¶åœ¨æ­¤å¤„åˆ†äº«æ‚¨çš„ç­”æ¡ˆâ†’
