# Automatically close issues fixed in pull requests that doesn't target the default branch.

name: ðŸš«ã€€Auto Close Fixed Issues
on:
  pull_request_target:
    types: [closed]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token
      - uses: wow-actions/auto-close-fixed-issues@v1
        with:
          GITHUB_TOKEN: ${{ env.bot_token }}
          comment: |
            This issue was closed by #{{ pr }}.
