name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ã€€Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: ğŸ‰ã€€Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸš§ Install
        run: |
          npm i pnpm@latest -g
          pnpm install

      - name: ğŸš€ã€€Build
        run: pnpm run build

      - name: âœ…ã€€Test
        run: pnpm run test:coverage

      - name: ğŸ’¡ Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/coverage-final.json
          flags: x6
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
