name: ğŸ‘·  CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  run:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: ğŸ‰ Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: ğŸš§ Prepare Environment
      run: |
        npm install -g yarn
        npm install -g lerna
    - name: ğŸš€ Bootstrap
      run: |
        yarn bootstrap
    - name: ğŸ“¦ Build
      run: |
        yarn build:dev
    - name: ğŸš¨ Test
      run: |
        yarn test
    - name: ğŸ’„ Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./packages/x6/test/coverage/lcov.info
