name: ðŸ¥¤ã€€GitLeaks

on: [push, pull_request_target]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '1'
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O .gitleaks.toml https://raw.githubusercontent.com/ycjcl868/gitleaks/master/.gitleaks.toml
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
