name: ğŸ·ï¸ã€€Label(File Paths)
on: pull_request
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”‘ã€€Generate token
        uses: bubkoo/use-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: ğŸ—ã€€Label
        uses: actions/labeler@v2
        with:
          repo-token: "${{ steps.generate_token.outputs.token }}"
          configuration-path: .github/workflows/config/pr-label-file-paths.yml
