name: ğŸ·ï¸ã€€Label(Patch Size)
on: pull_request
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ğŸ”‘ã€€Generate token
        id: generate_token
        uses: ./.github/actions/app-token
      - name: ğŸ—ã€€Label
        uses: pascalgn/size-label-action@v0.1.1
        env:
          GITHUB_TOKEN: "${{ steps.generate_token.outputs.token }}"
          IGNORED: "!.gitignore\nyarn.lock"
