name: ğŸ·ï¸ã€€Label(Patch Size)
on: pull_request
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”‘ã€€Generate token
        id: generate_token
        uses: ../actions/app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: ğŸ—ã€€Label
        uses: pascalgn/size-label-action@v0.1.1
        env:
          GITHUB_TOKEN: "${{ steps.generate_token.outputs.token }}"
          IGNORED: "!.gitignore\nyarn.lock"
