name: üè∑Ô∏è„ÄÄLabel(Patch Size)
on: pull_request
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@v0.1.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          IGNORED: "!.gitignore\nyarn.lock"
