# Label a PR according to the packages it involves, based on changed files
# and the rules defined in .github/workflows/config/pr-label-file-paths.yml

name: üè∑Ô∏è„ÄÄLabel(File Paths)
on: pull_request_target
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ env.bot_token }}
          configuration-path: .github/workflows/config/pr-label-file-paths.yml
