name: üè∑Ô∏è„ÄÄLabel(Patch Size)
on: pull_request
jobs:
  run:
    steps:
      - uses: actions/checkout@v2
      - uses: pascalgn/size-label-action@v0.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.bot_token }}
          IGNORED: "!.gitignore\nyarn.lock"
