# Automatically label a PR depending on the PR's status

name: ğŸ·ï¸ã€€Label(Status)
on:
  pull_request_target:
    types: [opened, closed, edited, reopened, synchronize, ready_for_review]
  workflow_run:
    workflows: ['ğŸ·ï¸ã€€Label(Status) Dummy'] # the workflow in step 1
    types: [requested]
permissions:
  contents: read
  pull-requests: write
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/pr-triage@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_ID: ${{ github.event.workflow_run.id }}
