name: ðŸ“†ã€€Weekly Report
on:
  schedule:
    - cron: '30 17 * * 5'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token
      - uses: wow-actions/activity-report@v1
        with:
          GITHUB_TOKEN: ${{ env.bot_token }}
