name: ðŸš«ã€€Close Stale Issues
on:
  schedule:
  - cron: "0 0 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
        stale-pr-message: 'This pr is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
        days-before-stale: 60
        days-before-close: 7
        stale-issue-label: 'no-issue-activity'
        exempt-issue-label: 'awaiting-approval'
        stale-pr-label: 'no-pr-activity'
        exempt-pr-label: 'awaiting-approval'
