name: ðŸ”„ã€€Sync Labels
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/config/labels.yml
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ env.bot_token }}
        with:
          manifest: .github/workflows/config/labels.yml
